### ISSUE TITLE
Lame is not defined

### ISSUE THREAD

**Issue by manu-ust** [closeio/mic-recorder-to-mp3#10]
While integrating inside the angular Application, it is showing like this,

index.js:15500 Uncaught ReferenceError: Lame is not defined
    at index.js:15500
    at index.js:2
    at Object../node_modules/mic-recorder-to-mp3/dist/index.js (index.js:5)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/robotic/robotic.component.ts (main.js:592)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app-routing.module.ts (main.js:106)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app.module.ts (app.component.ts:8)
    at __webpack_require__ (bootstrap:79)
(anonymous) @ index.js:15500
(anonymous) @ index.js:2
./node_modules/mic-recorder-to-mp3/dist/index.js @ index.js:5
__webpack_require__ @ bootstrap:79
./src/app/robotic/robotic.component.ts @ main.js:592
__webpack_require__ @ bootstrap:79
./src/app/app-routing.module.ts @ main.js:106
__webpack_require__ @ bootstrap:79
./src/app/app.module.ts @ app.component.ts:8
__webpack_require__ @ bootstrap:79
./src/main.ts @ main.ts:1
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
client:52 [WDS] Live Reloading enabled.

**Comment by madeInLagny** [comment]
I have the same problem. Did you find a solution to it ?

**Comment by buzinas** [comment]
If you share a reproducible issue, I may try to fix it.

**Comment by manu-ust** [comment]
> I have the same problem. Did you find a solution to it ?

I just added source for lame directly to the html file. i know its not a good fix.

**Comment by buzinas** [comment]
@manu-ust Can you share a minimal reproducible [CodeSandbox](https://codesandbox.io/)?

**Comment by buzinas** [comment]
I'll close this issue for inactivity – will reopen in case someone shares a minimal reproducible repo/sandbox etc.

**Comment by calvinckho** [comment]
#32 fixes this bug

**Comment by prasoonthakur8** [comment]
Untill admin approves changes, you can use 
`npm i mic-recorder-to-mp3-fixed`

and can be used as:
`import MicRecorder from 'mic-recorder-to-mp3-fixed';`

I have merged the [32](https://github.com/closeio/mic-recorder-to-mp3/pull/32) in this package.


Thanks
