### ISSUE TITLE
Permission Denied in Opera

### ISSUE THREAD

**Issue by MubashirEbad** [closeio/mic-recorder-to-mp3#12]
Hi,
I am trying to record audio from multiple browsers, it is working perfectly fine for Chrome, Safari, Firefox.
But when tried in Opera, it asks for Audio access as it asks for other browsers as well, even if I allow access to Microphone, it still throws **Permission Denied** Error.
`DOMException: Permission denied by system`.

**Comment by MubashirEbad** [comment]
Nevermind, found out its an issue with Opera. It does not let you record using Mac.

**Comment by buzinas** [comment]
Cool, thanks for reporting!
