### ISSUE TITLE
TypeError: Cannot read property 'finish' of undefined

### ISSUE THREAD

**Issue by GihanRangana** [closeio/mic-recorder-to-mp3#14]
getting TypeError: Cannot read property 'finish' of undefined from mic-recorder-to-mp3/dist/index.js:15941

**Comment by brunoqs** [comment]
Please if u are using React, try to use Component Class instead of Function Component, it works for me

**Comment by crbentle** [comment]
It works in a Functional Component if you memoize the recorder.
`const recorder = useMemo(() => new MicRecorder({ bitRate: 128 }), []);`

Without this, the recorder you used to start() is not the same one used to stop() and that is causing the problem.

**Comment by cystudyeverday** [comment]
crbentle 's method saves my day!!Thanks a lot

**Comment by buzinas** [comment]
This issue only happen when you're trying to finish a non-started recorder. Probably related to https://github.com/closeio/mic-recorder-to-mp3/issues/14#issuecomment-598175708.

**Comment by JeremiahUL** [comment]
Anyone having this issue. Try to confirm that .start() is being called first
