### ISSUE TITLE
GPGL issue for lamejs

### ISSUE THREAD

**Issue by quantaz** [closeio/mic-recorder-to-mp3#16]
We are using this module that comes under MIT licence, but this module is dependent on lamejs that comes under GPGL licence.
Do we have to confirm to lamejs for using this module?

**Comment by buzinas** [comment]
Disclaimer: I'm not a lawyer and I don't know much about licenses, but:

Lame license is LPGL, actually. So if it's a commercial application, you probably need to fully acknowledge that you are using LAME, and link to [their web site](https://lame.sourceforge.net).

**Comment by bradisbell** [comment]
It seems that this package cannot/should not be licensed as "MIT".
