### ISSUE TITLE
Red dot on google chrome

### ISSUE THREAD

**Issue by Lekterx** [closeio/mic-recorder-to-mp3#19]
Hi, thanks a lot for this great work !
I just found that in chrome, the tab where my app is running keeps a red dot even after I changed page and am not recording anymore. 
Is there any action I should take to close this when the recording is over ?
Thanks a lot !

**Comment by kauly** [comment]
Here the red dot disappears  after call the stop() method on the MicRecorder instance.

**Comment by buzinas** [comment]
You just need to call `.stop()` and the red dot will be gone.
