### ISSUE TITLE
TypeError: this.lameEncoder is undefined

### ISSUE THREAD

**Issue by fodaysahid** [closeio/mic-recorder-to-mp3#28]
![Screenshot](https://user-images.githubusercontent.com/11199402/92825990-b4739c00-f3bf-11ea-9fe9-f086aa82dac3.png)
 When I Click on the Stop recording button. It throws the error above.

**Comment by parnasmi** [comment]
I am having the same error in Safari when using in React. There is no error in other browsers

**Comment by buzinas** [comment]
Can you share the complete code?

It looks like you're calling `Mp3Recorder.stop` as it was a singleton, which won't work.

Also, maybe you're creating `Mp3Recorder` into a React's `render` function, and if that's the case, you'll end up with different instances of the recorder, as every time the `render` function is executed, it will create a new `Mp3Recorder`. In such case, if you're using a functional component, you should instantiate the recorder with `useMemo`, eg:

```js
const recorder = useMemo(() => new MicRecorder(...), []);
```

Then React will make sure your recorder instance remains the same across renders.

**Comment by fodaysahid** [comment]
Thanks. Have fixed the issue. I wasn't using useMemo()
