### ISSUE TITLE
Firefox issue: OverconstrainedError on start recording

### ISSUE THREAD

**Issue by danirrivas** [closeio/mic-recorder-to-mp3#3]
When triggering the recorder.start() action the following error happens (Firefox 59.0.2):

```
MediaStreamError
​constraint: "deviceId"
​message: "Constraints could be not satisfied."
​name: "OverconstrainedError"
​stack: ""
```

It can be easily reproducible with the [Live example on jsfiddle](https://jsfiddle.net/8u5fbpx6/1/).

Hope this helps to make this app great again :-)

**Comment by jonathan-s** [comment]
Also having this issue.

**Comment by benmackerras** [comment]
This could be fixed by simply removing the constraint from getUserMedia in index.js (I'm not even sure what the point of this constrain is since its just setting the deviceId to 'default' which I'm guessing would be the default value anyway)
